# Generated by Django 3.0.3 on 2020-04-10 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messages',
            name='Mess_reg',
        ),
        migrations.AddField(
            model_name='messages',
            name='Name',
            field=models.CharField(max_length=200),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Guest_contact',
        ),
    ]
