# Generated by Django 3.0.3 on 2020-04-11 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0003_auto_20200410_1730'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='Paid_amount',
            field=models.FloatField(),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='exam',
            name='Lock',
            field=models.CharField(max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registration',
            name='Reviews',
            field=models.TextField(),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subject',
            name='Chapter_text_content',
            field=models.TextField(),
            preserve_default=False,
        ),
    ]
