# Generated by Django 3.0.3 on 2020-04-12 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0004_auto_20200411_1223'),
    ]

    operations = [
        migrations.AddField(
            model_name='learning_progress',
            name='Course_chapter_name',
            field=models.CharField(max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='learning_progress',
            name='Begin_timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='learning_progress',
            name='Completion_timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='registration',
            name='Qualification',
            field=models.TextField(),
        ),
    ]
