# Generated by Django 3.0.3 on 2020-04-12 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0005_auto_20200412_1609'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='Num_of_images',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='Num_of_paragraphs',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='Num_of_videos',
        ),
    ]
