# Generated by Django 3.0.3 on 2020-04-13 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0006_auto_20200412_2116'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='Teacher_email',
            field=models.EmailField(max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='feedback',
            name='Teacher_name',
            field=models.CharField(max_length=200),
            preserve_default=False,
        ),
    ]
