# Generated by Django 3.0.3 on 2020-04-13 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0008_exam_results_teacher_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='Reviews',
        ),
    ]
