# Generated by Django 3.0.6 on 2020-09-17 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0009_remove_registration_reviews'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='Certificate',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
