# Generated by Django 3.0.6 on 2020-09-17 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0010_auto_20200917_1218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='Certificate',
            field=models.CharField(max_length=200),
            preserve_default=False,
        ),
    ]
