# Generated by Django 3.0.6 on 2020-12-13 06:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('learn', '0012_remove_exam_results_teacher_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='userr',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
