# Generated by Django 3.0.6 on 2021-01-03 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0017_enrollment_notify'),
    ]

    operations = [
        migrations.AddField(
            model_name='learning_progress',
            name='Teacher_email',
            field=models.EmailField(max_length=200, null=True),
        ),
    ]
