# Generated by Django 3.0.6 on 2021-01-18 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0018_learning_progress_teacher_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learning_progress',
            name='Course_chapter_content_name',
            field=models.ImageField(null=True, upload_to='media'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='Chapter_Content_name',
            field=models.ImageField(null=True, upload_to='media'),
        ),
    ]
