# Generated by Django 4.1.7 on 2023-03-08 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0021_newsletter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='Approval_status',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='Name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='Certificate',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='Course_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='Enrollment_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='Student_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='Subject_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='Teacher_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='Teacher_response',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='exam',
            name='Course_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='exam',
            name='Lock',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='exam',
            name='Student_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='exam',
            name='Subject_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='exam',
            name='Teacher_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='exam_results',
            name='Grade',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='exam_results',
            name='Student_email',
            field=models.EmailField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='exam_results',
            name='Student_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='exam_results',
            name='Subject_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='exam_results',
            name='Teacher_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='exam_results',
            name='Time_stop',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='Course_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='Feedback_text',
            field=models.TextField(default='Nil', null=True),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='Student_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='Subject_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='Teacher_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='learning_progress',
            name='Begin_timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='learning_progress',
            name='Completion_timestamp',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='learning_progress',
            name='Course_chapter_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='learning_progress',
            name='Course_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='learning_progress',
            name='Status',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='learning_progress',
            name='Student_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='learning_progress',
            name='Subject_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='messages',
            name='Category',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='messages',
            name='Message_content',
            field=models.TextField(default='Nil', null=True),
        ),
        migrations.AlterField(
            model_name='messages',
            name='Name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='registration',
            name='Email',
            field=models.EmailField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='registration',
            name='First_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='registration',
            name='Image',
            field=models.ImageField(null=True, upload_to='media'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='Last_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='registration',
            name='Num_of_courses_completed',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='registration',
            name='Num_of_courses_enrolled',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='registration',
            name='Password',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='registration',
            name='User_role',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='requests',
            name='Name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='requests',
            name='New_password',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='requests',
            name='Old_password',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='requests',
            name='User_category',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='Chapter_Content_type',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='Chapter_title',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='Course_title',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='Language',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='Subject_title',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
