# Generated by Django 4.1.7 on 2023-03-21 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0023_alter_blogs_blog_content_alter_blogs_date_blog_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='Course_completion_status',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
