# Generated by Django 4.1.7 on 2023-03-21 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0024_enrollment_course_completion_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='Course_fee',
            field=models.IntegerField(null=True),
        ),
    ]
