# Generated by Django 4.2 on 2023-04-29 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0025_enrollment_course_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='Registration_fee',
            field=models.IntegerField(null=True),
        ),
    ]
