# Generated by Django 4.2.3 on 2023-07-19 06:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0027_attendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='atten_enroll',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='att_to_enroll', to='learn.enrollment'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='atten_tea',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='att_to_tea', to='learn.registration'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='atten_stud',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='att_to_stud', to='learn.registration'),
        ),
    ]
