# Generated by Django 4.2.3 on 2023-07-19 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0028_attendance_atten_enroll_attendance_atten_tea_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='atten_tea',
        ),
        migrations.AddField(
            model_name='attendance',
            name='Teacher',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
