# Generated by Django 4.2.3 on 2023-07-19 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0029_remove_attendance_atten_tea_attendance_teacher'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('achievement', models.CharField(max_length=200)),
            ],
        ),
    ]
