# Generated by Django 4.2.3 on 2023-07-19 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0030_student'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
    ]
