# Generated by Django 4.2.3 on 2023-07-20 05:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0031_delete_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='Live',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateTimeField(auto_now_add=True, null=True)),
                ('title', models.CharField(max_length=200, null=True)),
                ('enrol', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='att_to_enrol', to='learn.enrollment')),
            ],
        ),
    ]
