# Generated by Django 4.2.3 on 2023-07-20 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0033_rename_date_live_ldate_live_link'),
    ]

    operations = [
        migrations.RenameField(
            model_name='live',
            old_name='lDate',
            new_name='ldate',
        ),
    ]
