# Generated by Django 4.2.3 on 2023-07-20 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0034_rename_ldate_live_ldate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='live',
            name='ldate',
            field=models.DateTimeField(null=True),
        ),
    ]
