# Generated by Django 4.2.3 on 2023-07-20 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0035_alter_live_ldate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='live',
            name='title',
        ),
    ]
