# Generated by Django 4.2.3 on 2023-07-24 06:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0037_alter_live_ldate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignment_topic', models.CharField(max_length=200, null=True)),
                ('assignment_upload', models.FileField(null=True, upload_to='')),
                ('assignment_upload_ans', models.FileField(null=True, upload_to='')),
                ('total_marks', models.CharField(max_length=200, null=True)),
                ('acquired_marks', models.CharField(max_length=200, null=True)),
                ('start_date', models.DateField(null=True)),
                ('submission_date', models.DateField(null=True)),
                ('assign_subject', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignment_to_subject', to='learn.subject')),
                ('teacher_reg', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignment_tea_reg', to='learn.registration')),
            ],
        ),
    ]
