# Generated by Django 4.2.3 on 2023-07-25 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0039_assignment_result_remove_assignment_acquired_marks_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='pass_percent',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
