# Generated by Django 4.2.3 on 2023-07-25 10:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0042_assignment_result_acquired_pass_percent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam_register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ex_reg_st', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exam_register_student', to='learn.registration')),
                ('ex_reg_sub', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exam_register_subject', to='learn.subject')),
                ('ex_reg_tea', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exam_register_teacher', to='learn.registration')),
            ],
        ),
    ]
