# Generated by Django 4.2.3 on 2023-07-26 05:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0043_exam_register'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject_st_stop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(null=True)),
                ('end_date', models.DateField(null=True)),
                ('sub_st_stop_sub', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Subject_st_stop_to_subject', to='learn.subject')),
            ],
        ),
    ]
