# Generated by Django 4.2.3 on 2023-07-26 05:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0044_subject_st_stop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject_st_stop',
            name='sub_st_stop_sub',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Subject_st_stop_to_subject', to='learn.subject'),
        ),
    ]
