# Generated by Django 4.2.3 on 2023-07-26 10:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0045_alter_subject_st_stop_sub_st_stop_sub'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam_register',
            name='ex_reg_st_enroll',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exam_register_student_enrollment', to='learn.enrollment'),
        ),
    ]
