# Generated by Django 4.2.3 on 2023-08-02 06:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0046_exam_register_ex_reg_st_enroll'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Category_title', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Chapter_title', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Chapter_Content', models.FileField(null=True, upload_to='media')),
                ('Chapter_text_content', models.TextField(null=True)),
                ('Chapter_Content_type', models.CharField(max_length=200, null=True)),
                ('cont_cha', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='learn.chapter')),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Course_title', models.CharField(max_length=200, null=True)),
                ('Course_brief', models.TextField(null=True)),
                ('Course_duration', models.IntegerField(null=True)),
                ('Course_fee', models.FloatField(null=True)),
                ('Language', models.CharField(max_length=200, null=True)),
                ('cou_cat', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Course_to_category', to='learn.category')),
            ],
        ),
        migrations.CreateModel(
            name='Course_st_stop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(null=True)),
                ('end_date', models.DateField(null=True)),
                ('cou_st_stop_cou', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Course_st_stop_to_course', to='learn.course')),
            ],
        ),
        migrations.RemoveField(
            model_name='subject_st_stop',
            name='sub_st_stop_sub',
        ),
        migrations.RenameField(
            model_name='enrollment',
            old_name='Course_name',
            new_name='Payment_status',
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='assign_subject',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='Teacher',
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='Attendance',
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='Course_fee',
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='Is_paid_subscription',
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='Paid_amount',
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='Student_email',
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='Student_name',
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='Subject_name',
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='Teacher_email',
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='Teacher_name',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='Course_name',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='Exam_reg',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='Student_email',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='Student_name',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='Subject_name',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='Teacher_name',
        ),
        migrations.RemoveField(
            model_name='exam_register',
            name='ex_reg_sub',
        ),
        migrations.RemoveField(
            model_name='exam_results',
            name='Exam_res_reg',
        ),
        migrations.RemoveField(
            model_name='exam_results',
            name='Student_email',
        ),
        migrations.RemoveField(
            model_name='exam_results',
            name='Student_name',
        ),
        migrations.RemoveField(
            model_name='exam_results',
            name='Subject_name',
        ),
        migrations.RemoveField(
            model_name='exam_results',
            name='Teacher_name',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='Course_name',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='Student_email',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='Student_name',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='Subject_name',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='Teacher_email',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='Teacher_name',
        ),
        migrations.RemoveField(
            model_name='learning_progress',
            name='Course_chapter_content_name',
        ),
        migrations.RemoveField(
            model_name='learning_progress',
            name='Course_chapter_name',
        ),
        migrations.RemoveField(
            model_name='learning_progress',
            name='Course_name',
        ),
        migrations.RemoveField(
            model_name='learning_progress',
            name='Student_email',
        ),
        migrations.RemoveField(
            model_name='learning_progress',
            name='Student_name',
        ),
        migrations.RemoveField(
            model_name='learning_progress',
            name='Subject_name',
        ),
        migrations.RemoveField(
            model_name='learning_progress',
            name='Teacher_email',
        ),
        migrations.RemoveField(
            model_name='messages',
            name='Category',
        ),
        migrations.RemoveField(
            model_name='messages',
            name='From_email',
        ),
        migrations.RemoveField(
            model_name='messages',
            name='Name',
        ),
        migrations.RemoveField(
            model_name='messages',
            name='To_email',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='Email',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='First_name',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='Last_name',
        ),
        migrations.AddField(
            model_name='attendance',
            name='atten_tea',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='att_to_teacher', to='learn.registration'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='enrol_tea',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teacher_teaching', to='learn.registration'),
        ),
        migrations.AddField(
            model_name='exam',
            name='Exam_reg_st',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exam_to_student', to='learn.registration'),
        ),
        migrations.AddField(
            model_name='exam',
            name='Exam_reg_tea',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exam_to_teacher', to='learn.registration'),
        ),
        migrations.AddField(
            model_name='exam_results',
            name='Exam_res_reg_st',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exam_res_to_student', to='learn.registration'),
        ),
        migrations.AddField(
            model_name='exam_results',
            name='Exam_res_reg_tea',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exam_res_to_teacher', to='learn.registration'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='Feed_tea_reg',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedback_tea_reg', to='learn.registration'),
        ),
        migrations.AddField(
            model_name='learning_progress',
            name='Learn_p_tea_reg',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='learning_progress_to_tea_reg', to='learn.registration'),
        ),
        migrations.AddField(
            model_name='messages',
            name='From_reg',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='from_message', to='learn.registration'),
        ),
        migrations.AddField(
            model_name='messages',
            name='To_reg',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='to_message', to='learn.registration'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='atten_stud',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='att_to_student', to='learn.registration'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='Certificate',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='enrol_reg',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_enrolled', to='learn.registration'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='Feed_reg',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedback_st_reg', to='learn.registration'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='Feedback_text',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='Submission_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='learning_progress',
            name='Learn_p_reg',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='learning_progress_to_st_reg', to='learn.registration'),
        ),
        migrations.AlterField(
            model_name='messages',
            name='Message_content',
            field=models.TextField(null=True),
        ),
        migrations.DeleteModel(
            name='Subject',
        ),
        migrations.DeleteModel(
            name='Subject_st_stop',
        ),
        migrations.AddField(
            model_name='course',
            name='cou_reg',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Course_to_registration', to='learn.registration'),
        ),
        migrations.AddField(
            model_name='chapter',
            name='cha_cou',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='learn.course'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='assign_course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignment_to_course', to='learn.course'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='enrol_cou',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='course_enrolled', to='learn.course'),
        ),
        migrations.AddField(
            model_name='exam',
            name='Exam_cou',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exam_to_course', to='learn.course'),
        ),
        migrations.AddField(
            model_name='exam_register',
            name='ex_reg_cou',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exam_register_course', to='learn.course'),
        ),
        migrations.AddField(
            model_name='exam_results',
            name='Exam_res_cou',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exam_res_to_course', to='learn.course'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='Feed_cou',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedback_to_course', to='learn.course'),
        ),
        migrations.AddField(
            model_name='learning_progress',
            name='Learn_p_cnt',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='learning_progress_to_content', to='learn.content'),
        ),
    ]
