# Generated by Django 4.2.3 on 2023-08-02 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0047_category_chapter_content_course_course_st_stop_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='Registration_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
