# Generated by Django 4.2.3 on 2023-08-02 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0049_alter_blogs_date_blog'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guest_messages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200, null=True)),
                ('Email', models.CharField(max_length=200, null=True)),
                ('Message_content', models.TextField(null=True)),
            ],
        ),
    ]
