# Generated by Django 4.2.3 on 2023-08-02 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0051_remove_requests_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='assign_course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assignment_to_course', to='learn.course'),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='cha_cou',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='learn.course'),
        ),
        migrations.AlterField(
            model_name='content',
            name='cont_cha',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='learn.chapter'),
        ),
        migrations.AlterField(
            model_name='course',
            name='cou_cat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Course_to_category', to='learn.category'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='enrol_cou',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course_enrolled', to='learn.course'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='Exam_cou',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exam_to_course', to='learn.course'),
        ),
        migrations.AlterField(
            model_name='exam_register',
            name='ex_reg_cou',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exam_register_course', to='learn.course'),
        ),
        migrations.AlterField(
            model_name='exam_results',
            name='Exam_res_cou',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exam_res_to_course', to='learn.course'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='Feed_cou',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feedback_to_course', to='learn.course'),
        ),
        migrations.AlterField(
            model_name='learning_progress',
            name='Learn_p_cnt',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='learning_progress_to_content', to='learn.content'),
        ),
    ]
