# Generated by Django 4.2.3 on 2023-08-20 06:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0054_category_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='live',
            name='liv_tea',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='liv_to_tea_reg', to='learn.registration'),
        ),
        migrations.AlterField(
            model_name='live',
            name='enrol',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='liv_to_enrol', to='learn.enrollment'),
        ),
    ]
